from olx.settings import *

SECRET_KEY = env('SECRET_KEY')

DEBUG = True

CSRF_TRUSTED_ORIGINS = []

ALLOWED_HOSTS = ['*']


POSTGRES_MAIN_DB_NAME = env("POSTGRES_MAIN_DB_NAME")
POSTGRES_MAIN_DB_USER = env("POSTGRES_MAIN_DB_USER")
POSTGRES_MAIN_DB_PASSWORD = env("POSTGRES_MAIN_DB_PASSWORD")

POSTGRES_LOG_DB_NAME = env("POSTGRES_LOG_DB_NAME")
POSTGRES_LOG_DB_USER = env("POSTGRES_LOG_DB_USER")
POSTGRES_LOG_DB_PASSWORD = env("POSTGRES_LOG_DB_PASSWORD")

DATABASES['default'] = {
    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    'NAME': f'{POSTGRES_MAIN_DB_NAME}',
    'USER': f'{POSTGRES_MAIN_DB_USER}',
    'PASSWORD': f'{POSTGRES_MAIN_DB_PASSWORD}',
    'HOST': 'db',
    'PORT': '5432',
}

DATABASES['log_db'] = {
    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    'NAME': f'{POSTGRES_LOG_DB_NAME}',
    'USER': f'{POSTGRES_LOG_DB_USER}',
    'PASSWORD': f'{POSTGRES_LOG_DB_PASSWORD}',
    'HOST': 'db',
    'PORT': '5432',
}


