# Generated by Django 6.0.4 on 2026-05-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('olx', 'olx'), ('ejobs', 'ejobs')], max_length=255, verbose_name='source')),
                ('title', models.CharField(max_length=1000, verbose_name='title')),
                ('title_translation', models.CharField(blank=True, max_length=1000, null=True, verbose_name='title translation')),
                ('company', models.CharField(blank=True, max_length=1000, null=True, verbose_name='company')),
                ('city', models.CharField(blank=True, max_length=1000, null=True, verbose_name='city')),
                ('date', models.CharField(blank=True, max_length=1000, null=True, verbose_name='date')),
                ('link', models.CharField(blank=True, max_length=3000, null=True, verbose_name='link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='JobLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=3000, verbose_name='link')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraper_active', models.BooleanField(default=False)),
                ('translated_language', models.CharField(choices=[('en', 'en'), ('fa', 'fa')], default='en', max_length=255, verbose_name='translated language')),
            ],
        ),
    ]
